#Array Creation

In [ ]:
import numpy as np

0-D Array

In [ ]:
arr = np.array(42)

print(arr)

#array dimension size
print(arr.ndim)



42
0


1-D Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

#array dimension size
print(arr.ndim)

[1 2 3 4 5]
1


2-D Array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

#array dimension size
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


3-D Array

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

#array dimension size
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


#Numpy Array Indexing

In [ ]:
# in 1-d array
arr = np.array([1, 2, 3, 4])

print(arr[1])

# in 1-d array

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

#in 3-d array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


2
2nd element on 1st row:  2
6


# Array Manipulation

In 1-d array


In [ ]:

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Reshape to a 5x1 array (2D)
reshaped = arr.reshape(5, 1)
print("Reshaped 1D to 2D (5x1):\n", reshaped)

# Flattening (stays the same in 1D)
flattened = arr.flatten()
print("Flattened (1D):", flattened)

# Create another 1D array for stacking
arange_arr = np.arange(6, 11)

# Stack arrays
stacked = np.stack((arr, arange_arr[:len(arr)]))
print("Stacked Array:\n", stacked)

# Horizontal and vertical stacking
hstacked = np.hstack((arr, arange_arr[:len(arr)]))
vstacked = np.vstack((arr, arange_arr[:len(arr)]))
print("Horizontally Stacked:\n", hstacked)
print("Vertically Stacked:\n", vstacked)


Reshaped 1D to 2D (5x1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Flattened (1D): [1 2 3 4 5]
Stacked Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontally Stacked:
 [ 1  2  3  4  5  6  7  8  9 10]
Vertically Stacked:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


in 2-D array

In [ ]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed = arr_2d.T
print("Transposed 2D Array:\n", transposed)

# Concatenating another 2D array vertically
arr2 = np.array([[7, 8, 9]])
concatenated = np.concatenate((arr_2d, arr2), axis=0)
print("Concatenated 2D Array (axis=0):\n", concatenated)

Transposed 2D Array:
 [[1 4]
 [2 5]
 [3 6]]
Concatenated 2D Array (axis=0):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


in 3-D array

In [ ]:
# Create a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original 3D Array:\n", arr_3d)

# Reshape the array to (3, 2, 2)
reshaped_3d = arr_3d.reshape(3, 2, 2)
print("Reshaped 3D Array (3x2x2):\n", reshaped_3d)

# Splitting the 3D array
split_3d = np.array_split(arr_3d, 2)
print("Split 3D Array (2 parts):\n", split_3d)

Original 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reshaped 3D Array (3x2x2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Split 3D Array (2 parts):
 [array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]])]


#Arithmetic operation on Arrays

in 1-D array

In [ ]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Addition
add_result = arr1 + arr2
print("1D Addition:", add_result)

# Subtraction
sub_result = arr1 - arr2
print("1D Subtraction:", sub_result)

# Multiplication
mul_result = arr1 * arr2
print("1D Multiplication:", mul_result)

# Division
div_result = arr1 / arr2
print("1D Division:", div_result)


1D Addition: [ 6  8 10 12]
1D Subtraction: [-4 -4 -4 -4]
1D Multiplication: [ 5 12 21 32]
1D Division: [0.2        0.33333333 0.42857143 0.5       ]


in 2-D array

In [ ]:
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Addition
add_result = arr1 + arr2
print("2D Addition:\n", add_result)

# Multiplication
mul_result = arr1 * arr2
print("2D Multiplication:\n", mul_result)

2D Addition:
 [[ 6  8]
 [10 12]]
2D Multiplication:
 [[ 5 12]
 [21 32]]


in 3-D array

In [ ]:
# Create two 3D arrays
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Addition
add_result = arr1 + arr2
print("3D Addition:\n", add_result)


3D Addition:
 [[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]


#Slicing in Arrays

in 1,2,3-D arrays

In [ ]:
# One-Dimensional (1D) Array
arr1d = np.array([10, 20, 30, 40, 50, 60])
print("1D Slice [1:4]:", arr1d[1:4])
print("1D Slice with step 2:", arr1d[::2])

# Two-Dimensional (2D) Array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Slice (Rows 0-1, Columns 1-2):\n", arr2d[0:2, 1:3])
print("2D Slice (First Column):", arr2d[:, 0])

# Three-Dimensional (3D) Array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Slice (First set, Columns 1-2):\n", arr3d[0, :, 1:3])
print("3D Slice (First Rows of all Depths):\n", arr3d[:, 0, :])


1D Slice [1:4]: [20 30 40]
1D Slice with step 2: [10 30 50]
2D Slice (Rows 0-1, Columns 1-2):
 [[2 3]
 [5 6]]
2D Slice (First Column): [1 4 7]
3D Slice (First set, Columns 1-2):
 [[2 3]
 [5 6]]
3D Slice (First Rows of all Depths):
 [[1 2 3]
 [7 8 9]]


#Shape Manipulation

In [ ]:
# One-Dimensional (1D) Array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape 1D to 2D (3 rows, 2 columns)
reshaped_1d = arr1d.reshape(3, 2)
print("Reshaped 1D to 2D (3x2):\n", reshaped_1d)

# Two-Dimensional (2D) Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose 2D array
transposed_2d = arr2d.T
print("Transpose of 2D Array:\n", transposed_2d)

# Flatten 2D array to 1D
flattened_2d = arr2d.flatten()
print("Flattened 2D to 1D:", flattened_2d)

# Three-Dimensional (3D) Array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Reshape 3D array to (4, 1, 2)
reshaped_3d = arr3d.reshape(4, 1, 2)
print("Reshaped 3D to (4x1x2):\n", reshaped_3d)




Reshaped 1D to 2D (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Transpose of 2D Array:
 [[1 4]
 [2 5]
 [3 6]]
Flattened 2D to 1D: [1 2 3 4 5 6]
Reshaped 3D to (4x1x2):
 [[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]
